### ISSUE TITLE
Is there a way to generate the spreadsheet?

### ISSUE THREAD

**Issue by m7vm7v** [orkhanahmadov/spreadsheet-translations#1]
Is there a way to generate the .xlsx document?

Use case - 
I have a file in `resources/lang/fr.json` with `{ ... "Title": "", ... }
I would like to be able to create the spreadsheet from that file.
Send it to the translation team.
Update the file and import the translations.

What are your thoughts on that?

**Comment by orkhanahmadov** [comment]
I don't think it has a use case for this package. Because it is a one-time thing you need to generate, after that it is not useful anymore. I think it needs to be handled per application.

But if it helps, here's the code I used when we first migrated from file-based translations to Excel.
```php
$translator = app('translator');
$translator->load('*', '*', 'fr');

$loaded = new \ReflectionProperty($translator, 'loaded');
$loaded->setAccessible(true);
$translations = $loaded->getValue($translator)['*']['*']['fr'];
```

`$translations` here will have an array translations list for the `fr` locale using the array key as the translation key and the array value as the actual translation. You can use it to generate your own one-time Excel spreadsheet.

**Comment by m7vm7v** [comment]
Hmm yeah, I get your reasoning on that, thanks.
What if we want continuous working on the file? For example, in the initial stage, I'd export all EN and FR into a spreadsheet, send it to my team for translation, and then I will import it back to my application. At a later stage when new functionality is introduced and new language strings are to be translated I'd want to have a way to export again with all current translations and the new string so that can be again sent to my team.

Hope that makes sense and justifies my original question/request.
